# **Data Cleaning & Preprocessing**
---

In [1]:
import pandas as pd
df=pd.read_csv(r'/kaggle/input/fulldata/v4.csv')

In [2]:
df.shape

(89375, 6)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89375 entries, 0 to 89374
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              89375 non-null  object
 1   title           89375 non-null  object
 2   authors         89375 non-null  object
 3   published_date  89375 non-null  object
 4   pdf_url         89375 non-null  object
 5   full_text       88137 non-null  object
dtypes: object(6)
memory usage: 4.1+ MB

### **Checking NULL's**
---

In [4]:
df.isna().sum()

id                   0
title                0
authors              0
published_date       0
pdf_url              0
full_text         1238
dtype: int64

In [5]:
pd.set_option('display.max_rows', None)
df[df['full_text'].isna()]['published_date']

108      1998-09-29
123      1998-12-10
143      1999-06-01
152      1999-09-03
170      2000-03-22
218      2000-03-01
219      2000-03-01
287      2001-03-02
438      2002-09-19
458      2002-11-09
545      2003-09-17
619      2004-04-22
886      2005-11-03
953      2006-05-12
966      2006-06-14
993      2006-08-07
1101     2007-04-11
1290     2008-03-08
1347     2008-06-27
1367     2008-06-08
1440     2008-10-18
1507     2008-12-04
1527     2009-01-06
1564     2009-03-26
1625     2009-04-18
1639     2009-04-03
1648     2009-05-28
1740     2009-07-03
1817     2009-10-08
1840     2009-11-15
1841     2009-11-15
1858     2009-12-27
2069     2010-06-29
2160     2010-07-04
2163     2010-08-30
2282     2010-11-01
2288     2010-12-28
2415     2011-03-24
2539     2011-05-01
2751     2011-07-08
2790     2011-08-18
2949     2011-10-11
3061     2012-01-20
3319     2012-04-11
3360     2012-05-11
3361     2012-05-11
3399     2012-05-01
3532     2012-06-15
3537     2012-06-13
3711     2012-07-04
3776     2012-08-27
3777     2012-08-25
3778     2012-08-25
3779     2012-08-25
3780     2012-08-25
3781     2012-08-25
3793     2012-08-14
3796     2012-08-10
3803     2012-08-08
3811     2012-09-29
3996     2012-10-08
4043     2012-11-13
4047     2012-11-12
4219     2013-01-29
4308     2013-01-19
4309     2013-01-19
4310     2013-01-19
4311     2013-01-19
4381     2013-01-10
4448     2013-01-09
4549     2013-02-26
4756     2013-02-01
5272     2013-04-24
5302     2013-04-15
5308     2013-04-13
5309     2013-04-13
5310     2013-04-13
5311     2013-04-13
5312     2013-04-13
5313     2013-04-13
5314     2013-04-13
5315     2013-04-13
5316     2013-04-13
5317     2013-04-13
5318     2013-04-13
5319     2013-04-13
5320     2013-04-13
5321     2013-04-13
5322     2013-04-13
5347     2013-04-02
5401     2013-05-02
5418     2013-06-25
5792     2013-12-28
5796     2013-12-25
5816     2013-12-20
5846     2013-12-09
5858     2013-12-03
6039     2014-01-09
6100     2014-02-14
6193     2014-03-01
6476     2014-07-23
6776     2014-11-05
6782     2014-11-03
6790     2014-12-30
6919     2015-01-07
7130     2015-04-21
7229     2015-05-12
7396     2015-07-17
7573     2015-09-18
7646     2015-10-21
7676     2015-10-12
7877     2015-12-16
7890     2015-12-13
7916     2015-12-04
8170     2016-03-27
8511     2016-05-20
8654     2016-06-23
8693     2016-06-17
8994     2016-08-26
9025     2016-08-19
9075     2016-08-06
9098     2016-08-02
9194     2016-09-14
9281     2016-10-25
9427     2016-11-29
9540     2016-11-12
9591     2016-11-04
9709     2016-12-13
9714     2016-12-13
9849     2017-01-24
9858     2017-01-22
9897     2017-01-12
9956     2017-02-24
9989     2017-02-19
10722    2017-05-09
10782    2017-05-01
10863    2017-06-19
10977    2017-06-05
11045    2017-07-25
11083    2017-07-20
11170    2017-07-11
11440    2017-08-05
11488    2017-09-29
11504    2017-09-27
11700    2017-09-12
11739    2017-09-07
11892    2017-10-15
12096    2017-11-20
12161    2017-11-15
12344    2017-12-24
12363    2017-12-21
12487    2017-12-04
12755    2018-02-26
12933    2018-02-13
13029    2018-02-04
13328    2018-03-02
13567    2018-04-11
13587    2018-04-10
13811    2018-05-22
13824    2018-05-21
13894    2018-05-17
13903    2018-05-17
13980    2018-05-10
14023    2018-05-07
14099    2018-06-29
14100    2018-06-29
14241    2018-06-17
15115    2018-09-27
15226    2018-09-19
15338    2018-09-11
15695    2018-10-14
15708    2018-10-12
15752    2018-10-10
15791    2018-10-06
16221    2018-11-06
16392    2018-12-21
16437    2018-12-17
16513    2018-12-11
16529    2018-12-09
16557    2018-12-06
16579    2018-12-04
16684    2019-01-25
16853    2019-01-07
16869    2019-01-04
16890    2019-01-02
16902    2019-01-01
17017    2019-02-18
17207    2019-03-29
17387    2019-03-12
17392    2019-03-11
17465    2019-03-06
17611    2019-04-25
17622    2019-04-24
18084    2019-05-23
18539    2019-06-24
18553    2019-06-23
19141    2019-07-10
19251    2019-07-01
19386    2019-08-18
19647    2019-09-23
19759    2019-09-17
19775    2019-09-16
19865    2019-09-11
20057    2019-09-03
20104    2019-10-30
20319    2019-10-11
20596    2019-11-21
20857    2019-11-04
21317    2020-01-22
21337    2020-01-21
21366    2020-01-19
21409    2020-01-15
21413    2020-01-15
21429    2020-01-14
21581    2020-02-27
21886    2020-02-07
22022    2020-03-26
22141    2020-03-16
22245    2020-03-09
22351    2020-03-01
22470    2020-04-23
22521    2020-04-20
22598    2020-04-13
22840    2020-05-27
22873    2020-05-25
22940    2020-05-19
23267    2020-05-01
23599    2020-06-11
24007    2020-07-17
24319    2020-08-30
24513    2020-08-19
24578    2020-08-14
24777    2020-08-02
24847    2020-09-28
24866    2020-09-26
24903    2020-09-24
25066    2020-09-19
25235    2020-09-14
25294    2020-09-11
25417    2020-09-06
25437    2020-09-04
25589    2020-10-28
25594    2020-10-28
25595    2020-10-27
25633    2020-10-27
25650    2020-10-26
25754    2020-10-22
25954    2020-10-18
25995    2020-10-16
26108    2020-10-14
26339    2020-10-08
26763    2020-11-24
26820    2020-11-22
26900    2020-11-18
27057    2020-11-13
27187    2020-11-09
27880    2020-12-15
28145    2020-12-07
28146    2020-12-07
28190    2020-12-06
28192    2020-12-06
28257    2020-12-03
28276    2020-12-03
28317    2020-12-02
28325    2020-12-02
28348    2020-12-01
28384    2021-01-29
28433    2021-01-27
28436    2021-01-27
28460    2021-01-27
28656    2021-01-19
28671    2021-01-19
28720    2021-01-17
29438    2021-02-17
29521    2021-02-15
30010    2021-02-01
30016    2021-02-01
30267    2021-03-24
30301    2021-03-23
30496    2021-03-17
30553    2021-03-15
30632    2021-03-12
30670    2021-03-11
30973    2021-03-02
31094    2021-04-27
31123    2021-04-26
31475    2021-04-16
31666    2021-04-12
32084    2021-05-28
32709    2021-05-08
32733    2021-05-07
32814    2021-05-05
32869    2021-05-03
33265    2021-06-21
33379    2021-06-17
33490    2021-06-15
34107    2021-06-02
34236    2021-07-29
34267    2021-07-28
34335    2021-07-27
34440    2021-07-23
34606    2021-07-16
34712    2021-07-14
35108    2021-07-03
35321    2021-08-25
35366    2021-08-24
35433    2021-08-21
35440    2021-08-20
35443    2021-08-20
35491    2021-08-19
35656    2021-08-12
35713    2021-08-11
35803    2021-08-09
35805    2021-08-09
35814    2021-08-08
35856    2021-08-06
36178    2021-09-26
36295    2021-09-22
36329    2021-09-21
36552    2021-09-16
36622    2021-09-15
36966    2021-09-06
36972    2021-09-06
36980    2021-09-06
37103    2021-09-01
37292    2021-10-27
37417    2021-10-24
37490    2021-10-22
37583    2021-10-19
37765    2021-10-15
38003    2021-10-11
38091    2021-10-08
38672    2021-11-22
38899    2021-11-15
38904    2021-11-15
39037    2021-11-11
39040    2021-11-11
39223    2021-11-05
39442    2021-12-30
39455    2021-12-30
39489    2021-12-29
39496    2021-12-28
39578    2021-12-24
39710    2021-12-20
39711    2021-12-20
39843    2021-12-16
39914    2021-12-14
39976    2021-12-13
40063    2021-12-10
40119    2021-12-09
40345    2021-12-03
40495    2022-01-30
40706    2022-01-25
40788    2022-01-22
41104    2022-01-12
41123    2022-01-12
41547    2022-03-26
41688    2022-03-23
41813    2022-03-21
41814    2022-03-21
42328    2022-03-08
42530    2022-03-02
42588    2022-03-01
42631    2022-08-30
42659    2022-08-29
42722    2022-08-26
42733    2022-08-25
42884    2022-08-22
43194    2022-08-12
43249    2022-08-10
43408    2022-08-04
43447    2022-08-02
43589    2022-09-28
43622    2022-09-28
43672    2022-09-27
43687    2022-09-26
43887    2022-09-21
44323    2022-09-10
44359    2022-09-09
44706    2022-10-28
44866    2022-10-26
44930    2022-10-25
45057    2022-10-23
45285    2022-10-19
45573    2022-10-14
45824    2022-10-11
46344    2022-11-29
46345    2022-11-29
46521    2022-11-26
46635    2022-11-23
46795    2022-11-20
47254    2022-11-10
47300    2022-11-09
47360    2022-11-07
47697    2022-12-30
47715    2022-12-29
47774    2022-12-27
47825    2022-12-25
47909    2022-12-22
48331    2022-12-12
48726    2022-12-02
49015    2023-01-26
49105    2023-01-24
49341    2023-01-16
49432    2023-01-13
49477    2023-01-12
49608    2023-01-07
49716    2023-01-03
49723    2023-01-03
49881    2023-03-29
50304    2023-03-21
50720    2023-03-13
50891    2023-03-09
51466    2023-04-27
51848    2023-04-20
51927    2023-04-19
52035    2023-04-17
52073    2023-04-15
52144    2023-04-14
52235    2023-04-12
52375    2023-04-09
52384    2023-04-08
52584    2023-04-04
52706    2023-04-01
52767    2023-05-30
52959    2023-05-27
53071    2023-05-26
54102    2023-05-16
54502    2023-05-09
54629    2023-05-06
54777    2023-05-04
54798    2023-05-04
54799    2023-05-04
54800    2023-05-04
54953    2023-05-01
55003    2023-06-29
55480    2023-06-20
55607    2023-06-17
55626    2023-06-17
55700    2023-06-16
55778    2023-06-15
55947    2023-06-13
56112    2023-06-09
56145    2023-06-09
56222    2023-06-08
56719    2023-06-01
56996    2023-07-27
57902    2023-07-10
57939    2023-07-10
57962    2023-07-09
57994    2023-07-08
58310    2023-07-03
58397    2023-08-30
58560    2023-08-28
58625    2023-08-28
58716    2023-08-25
59159    2023-08-18
59295    2023-08-16
59450    2023-08-13
59522    2023-08-11
59552    2023-08-11
59556    2023-08-11
59899    2023-08-04
60213    2023-09-29
60365    2023-09-27
60442    2023-09-26
60722    2023-09-21
60734    2023-09-21
60756    2023-09-21
61084    2023-09-17
61092    2023-09-17
61209    2023-09-14
61380    2023-09-12
61465    2023-09-10
61741    2023-09-05
61799    2023-09-04
61829    2023-09-04
61836    2023-09-04
61910    2023-09-01
62270    2023-10-26
62271    2023-10-26
62318    2023-10-25
62728    2023-10-20
62957    2023-10-17
63109    2023-10-16
63138    2023-10-15
63355    2023-10-12
63399    2023-10-11
63579    2023-10-10
63794    2023-10-07
63805    2023-10-07
63933    2023-10-05
63983    2023-10-05
64199    2023-10-02
64526    2023-11-28
64946    2023-11-21
64950    2023-11-21
65070    2023-11-20
65088    2023-11-20
65394    2023-11-15
65880    2023-11-08
65973    2023-11-07
65991    2023-11-06
66485    2023-12-29
66618    2023-12-26
66627    2023-12-26
66758    2023-12-22
67121    2023-12-18
67371    2023-12-15
67434    2023-12-14
67620    2023-12-12
67621    2023-12-12
67622    2023-12-12
67624    2023-12-12
67626    2023-12-12
67627    2023-12-12
67628    2023-12-12
67629    2023-12-12
67632    2023-12-12
67633    2023-12-12
67635    2023-12-12
67637    2023-12-12
67639    2023-12-12
67641    2023-12-12
67643    2023-12-12
67645    2023-12-12
67648    2023-12-12
67649    2023-12-12
67651    2023-12-12
67653    2023-12-12
67654    2023-12-12
67656    2023-12-12
67657    2023-12-12
67658    2023-12-12
67661    2023-12-12
67664    2023-12-12
67666    2023-12-12
67667    2023-12-12
67668    2023-12-12
67669    2023-12-12
67670    2023-12-12
67671    2023-12-11
67672    2023-12-11
67674    2023-12-11
67675    2023-12-11
67676    2023-12-11
67679    2023-12-11
67681    2023-12-11
67682    2023-12-11
67683    2023-12-11
67686    2023-12-11
67690    2023-12-11
67693    2023-12-11
67694    2023-12-11
67695    2023-12-11
67696    2023-12-11
67697    2023-12-11
67699    2023-12-11
67701    2023-12-11
67703    2023-12-11
67704    2023-12-11
67705    2023-12-11
67706    2023-12-11
67708    2023-12-11
67709    2023-12-11
67710    2023-12-11
67711    2023-12-11
67712    2023-12-11
67713    2023-12-11
67714    2023-12-11
67716    2023-12-11
67719    2023-12-11
67721    2023-12-11
67724    2023-12-11
67725    2023-12-11
67726    2023-12-11
67727    2023-12-11
67728    2023-12-11
67729    2023-12-11
67730    2023-12-11
67731    2023-12-11
67732    2023-12-11
67733    2023-12-11
67734    2023-12-11
67735    2023-12-11
67737    2023-12-11
67738    2023-12-11
67739    2023-12-11
67741    2023-12-11
67742    2023-12-11
67743    2023-12-11
67744    2023-12-11
67745    2023-12-11
67746    2023-12-11
67747    2023-12-11
67748    2023-12-11
67749    2023-12-11
67750    2023-12-11
67751    2023-12-11
67754    2023-12-11
67755    2023-12-11
67756    2023-12-11
67758    2023-12-11
67759    2023-12-11
67761    2023-12-11
67762    2023-12-11
67763    2023-12-11
67764    2023-12-11
67765    2023-12-11
67766    2023-12-11
67767    2023-12-11
67771    2023-12-11
67773    2023-12-11
67776    2023-12-11
67779    2023-12-11
67780    2023-12-11
67781    2023-12-11
67782    2023-12-11
67785    2023-12-10
67787    2023-12-10
67788    2023-12-10
67789    2023-12-10
67790    2023-12-10
67791    2023-12-10
67793    2023-12-10
67794    2023-12-10
67795    2023-12-10
67796    2023-12-10
67797    2023-12-10
67799    2023-12-10
67800    2023-12-10
67802    2023-12-10
67803    2023-12-10
67804    2023-12-10
67806    2023-12-10
67807    2023-12-10
67808    2023-12-10
67809    2023-12-10
67813    2023-12-10
67814    2023-12-10
67815    2023-12-10
67816    2023-12-10
67817    2023-12-10
67818    2023-12-10
67820    2023-12-10
67821    2023-12-10
67822    2023-12-10
67825    2023-12-10
67826    2023-12-10
67827    2023-12-10
67828    2023-12-10
67830    2023-12-10
67831    2023-12-10
67833    2023-12-10
67835    2023-12-10
67836    2023-12-10
67838    2023-12-10
67840    2023-12-10
67842    2023-12-10
67844    2023-12-10
67848    2023-12-09
67849    2023-12-09
67850    2023-12-09
67851    2023-12-09
67852    2023-12-09
67854    2023-12-09
67858    2023-12-09
67860    2023-12-09
67861    2023-12-09
67862    2023-12-09
67866    2023-12-09
67869    2023-12-09
67870    2023-12-09
67872    2023-12-09
67874    2023-12-09
67877    2023-12-09
67878    2023-12-09
67879    2023-12-09
67880    2023-12-09
67883    2023-12-09
67885    2023-12-09
67887    2023-12-09
67888    2023-12-09
67889    2023-12-09
67891    2023-12-09
67892    2023-12-09
67893    2023-12-09
67896    2023-12-09
67898    2023-12-08
67899    2023-12-08
67900    2023-12-08
67901    2023-12-08
67902    2023-12-08
67903    2023-12-08
67904    2023-12-08
67905    2023-12-08
67910    2023-12-08
67911    2023-12-08
67912    2023-12-08
67913    2023-12-08
67916    2023-12-08
67920    2023-12-08
67921    2023-12-08
67923    2023-12-08
67924    2023-12-08
67927    2023-12-08
67928    2023-12-08
67929    2023-12-08
67934    2023-12-08
67935    2023-12-08
67937    2023-12-08
67938    2023-12-08
67939    2023-12-08
67941    2023-12-08
67942    2023-12-08
67943    2023-12-08
67946    2023-12-08
67949    2023-12-08
67950    2023-12-08
67952    2023-12-08
67954    2023-12-08
67955    2023-12-08
67957    2023-12-08
67958    2023-12-08
67959    2023-12-08
67961    2023-12-08
67962    2023-12-08
67963    2023-12-08
67967    2023-12-08
67969    2023-12-08
67972    2023-12-07
67975    2023-12-07
67977    2023-12-07
67980    2023-12-07
67981    2023-12-07
67982    2023-12-07
67988    2023-12-07
67990    2023-12-07
67991    2023-12-07
67992    2023-12-07
67993    2023-12-07
67995    2023-12-07
67996    2023-12-07
67998    2023-12-07
67999    2023-12-07
68000    2023-12-07
68003    2023-12-07
68004    2023-12-07
68005    2023-12-07
68006    2023-12-07
68010    2023-12-07
68012    2023-12-07
68014    2023-12-07
68015    2023-12-07
68016    2023-12-07
68017    2023-12-07
68018    2023-12-07
68020    2023-12-07
68021    2023-12-07
68022    2023-12-07
68023    2023-12-07
68024    2023-12-07
68025    2023-12-07
68031    2023-12-07
68033    2023-12-07
68036    2023-12-07
68038    2023-12-07
68039    2023-12-07
68040    2023-12-07
68041    2023-12-07
68044    2023-12-07
68046    2023-12-07
68047    2023-12-07
68048    2023-12-07
68049    2023-12-07
68051    2023-12-07
68052    2023-12-07
68053    2023-12-07
68055    2023-12-07
68057    2023-12-07
68059    2023-12-07
68060    2023-12-07
68061    2023-12-07
68062    2023-12-07
68065    2023-12-06
68066    2023-12-06
68067    2023-12-06
68068    2023-12-06
68069    2023-12-06
68073    2023-12-06
68074    2023-12-06
68075    2023-12-06
68077    2023-12-06
68081    2023-12-06
68085    2023-12-06
68087    2023-12-06
68088    2023-12-06
68091    2023-12-06
68094    2023-12-06
68095    2023-12-06
68096    2023-12-06
68097    2023-12-06
68102    2023-12-06
68106    2023-12-06
68107    2023-12-06
68108    2023-12-06
68109    2023-12-06
68112    2023-12-06
68113    2023-12-06
68114    2023-12-06
68115    2023-12-06
68116    2023-12-06
68117    2023-12-06
68118    2023-12-06
68119    2023-12-06
68120    2023-12-06
68121    2023-12-06
68122    2023-12-06
68123    2023-12-06
68124    2023-12-06
68126    2023-12-06
68127    2023-12-06
68128    2023-12-06
68129    2023-12-06
68130    2023-12-06
68131    2023-12-06
68132    2023-12-06
68133    2023-12-06
68134    2023-12-05
68135    2023-12-05
68136    2023-12-05
68137    2023-12-05
68138    2023-12-05
68140    2023-12-05
68141    2023-12-05
68145    2023-12-05
68146    2023-12-05
68148    2023-12-05
68149    2023-12-05
68150    2023-12-05
68151    2023-12-05
68153    2023-12-05
68154    2023-12-05
68155    2023-12-05
68156    2023-12-05
68157    2023-12-05
68158    2023-12-05
68159    2023-12-05
68160    2023-12-05
68161    2023-12-05
68162    2023-12-05
68165    2023-12-05
68166    2023-12-05
68167    2023-12-05
68168    2023-12-05
68169    2023-12-05
68171    2023-12-05
68173    2023-12-05
68174    2023-12-05
68175    2023-12-05
68176    2023-12-05
68177    2023-12-05
68179    2023-12-05
68180    2023-12-05
68182    2023-12-05
68183    2023-12-05
68184    2023-12-05
68185    2023-12-05
68187    2023-12-05
68190    2023-12-05
68195    2023-12-05
68196    2023-12-05
68197    2023-12-05
68198    2023-12-05
68200    2023-12-05
68202    2023-12-05
68203    2023-12-05
68204    2023-12-05
68207    2023-12-05
68209    2023-12-05
68211    2023-12-05
68213    2023-12-05
68215    2023-12-05
68216    2023-12-05
68217    2023-12-05
68219    2023-12-05
68222    2023-12-05
68223    2023-12-05
68227    2023-12-04
68230    2023-12-04
68231    2023-12-04
68232    2023-12-04
68233    2023-12-04
68235    2023-12-04
68237    2023-12-04
68239    2023-12-04
68240    2023-12-04
68241    2023-12-04
68242    2023-12-04
68244    2023-12-04
68245    2023-12-04
68246    2023-12-04
68247    2023-12-04
68248    2023-12-04
68249    2023-12-04
68250    2023-12-04
68252    2023-12-04
68253    2023-12-04
68258    2023-12-04
68260    2023-12-04
68263    2023-12-04
68265    2023-12-04
68266    2023-12-04
68268    2023-12-04
68269    2023-12-04
68270    2023-12-04
68272    2023-12-04
68273    2023-12-04
68274    2023-12-04
68275    2023-12-04
68276    2023-12-04
68279    2023-12-04
68280    2023-12-04
68281    2023-12-04
68282    2023-12-04
68283    2023-12-04
68285    2023-12-04
68286    2023-12-04
68288    2023-12-04
68292    2023-12-04
68294    2023-12-04
68297    2023-12-04
68298    2023-12-04
68300    2023-12-04
68306    2023-12-04
68307    2023-12-04
68309    2023-12-04
68310    2023-12-04
68311    2023-12-04
68313    2023-12-04
68314    2023-12-04
68315    2023-12-04
68317    2023-12-04
68318    2023-12-04
68320    2023-12-04
68321    2023-12-04
68323    2023-12-04
68324    2023-12-04
68326    2023-12-04
68328    2023-12-04
68329    2023-12-03
68330    2023-12-03
68331    2023-12-03
68333    2023-12-03
68335    2023-12-03
68337    2023-12-03
68338    2023-12-03
68340    2023-12-03
68342    2023-12-03
68343    2023-12-03
68345    2023-12-03
68346    2023-12-03
68348    2023-12-03
68349    2023-12-03
68351    2023-12-03
68353    2023-12-03
68354    2023-12-03
68355    2023-12-03
68357    2023-12-03
68359    2023-12-03
68360    2023-12-02
68361    2023-12-02
68362    2023-12-02
68364    2023-12-02
68365    2023-12-02
68366    2023-12-02
68367    2023-12-02
68368    2023-12-02
68369    2023-12-02
68370    2023-12-02
68373    2023-12-02
68374    2023-12-02
68375    2023-12-02
68376    2023-12-02
68378    2023-12-02
68379    2023-12-02
68380    2023-12-02
68382    2023-12-02
68384    2023-12-02
68386    2023-12-02
68389    2023-12-02
68390    2023-12-02
68392    2023-12-02
68394    2023-12-01
68395    2023-12-01
68396    2023-12-01
68397    2023-12-01
68398    2023-12-01
68400    2023-12-01
68402    2023-12-01

In [6]:
df.iloc[108,5]

nan

### **Removing NULL's**
---

In [7]:
df.dropna(inplace=True)

In [8]:
df['full_text'].isna().sum()

0

In [9]:
df.shape

(88137, 6)

### **Cleaning Data**
---

In [10]:
df.iloc[5555,5]

'arXiv:1309.4408v2  [cs.AI]  18 Sep 2013\nLambda Dependency-Based Compositional Semantics\nPercy Liang\nSeptember 19, 2013\nAbstract\nThis short note presents a new formal language, lambda dependency-based compositional\nsemantics (lambda DCS) for representing logical forms in semantic parsing. By eliminating\nvariables and making existential quantiﬁcation implicit, lambda DCS logical forms are generally\nmore compact than those in lambda calculus.\n1\nIntroduction\nSemantic parsing is the task of mapping natural language utterances to logical forms in some\nformal language such as lambda calculus.\nThis short note describes lambda dependency-based\ncompositional semantics (lambda DCS), an alternate formal language which can be notationally\nsimpler than lambda calculus. Here is an example:1\n• Utterance: “people who have lived in Seattle”\n• Logical form (lambda calculus): λx.∃e.PlacesLived(x, e) ∧Location(e, Seattle)\n• Logical form (lambda DCS): PlacesLived.Location.Seattle\nAs one can see, lambda DCS attempts to remove explicit use of variables. This makes it simi-\nlar in spirit to dependency-based compositional semantics (DCS) (Liang et al. 2011), but DCS is\nrestricted to tree-structured logical forms, and is therefore not as expressive as lambda calculus.\nLambda DCS, on the other hand, borrows the use of variables and lambda abstraction from lambda\ncalculus when necessary to handle phenomena such as anaphora.\nLambda DCS was designed in the context of building a natural language interface into Free-\nbase (Bollacker et al. 2008), a large graph database, where the logical forms are database queries\n(see Berant et al. (2013) for our companion paper). Therefore, we will focus on representing the\nsemantics of noun phrases or wh-questions. Also, we will discuss only the semantics of the formal\nlanguage, not the compositional semantics of mapping natural language utterances into lambda\nDCS. Finally, this document assumes the reader has basic familiarity with lambda calculus in the\ncontext of natural language (see Carpenter (1998) for an introduction).\n1This example is based on the Freebase schema, which reiﬁes events (called compound value types in Freebase).\nHere, PlacesLived(x, e) denotes that a person x was involved in a living event e, and Location(e, Seattle) denotes\nthat the location of that event is Seattle. Other properties of e would include StartDate(e, ·) and EndDate(e, ·).\n1\n2\nDeﬁnition\nWe now present the full deﬁnition of lambda DCS. In the background, we have a knowledge base\nof assertions.\nLet E be a set of entities (e.g., Seattle ∈E), P be the set of properties (e.g.,\nPlaceOfBirth ∈E). Then K ⊂E ×P ×E is the knowledge base, which can be visualized as a directed\ngraph where nodes are entities and edges represent assertions in the knowledge graph. Also, let V\nbe a set of variables (e.g., x1, x2 ∈V).\nLet [condition] denote the truth value of the condition. For example, λx.[x = 3] denotes the\nfunction that returns true if and only if its argument is equal to 3.\nWe will now walk through each of the constructs in lambda DCS with concrete examples, and\nalso provide a formal deﬁnition of their semantics by providing a formal conversion to equivalent\nlambda calculus forms. Notationally, let JzK be the lambda calculus form corresponding to the\nlambda DCS form z. In the following deﬁnitions, let x, y denote fresh variables which are not used\nanywhere else.\nUnary base case\nThe simplest lambda DCS form is a single entity. For example,\nSeattle\n(1)\ndenotes the singleton set containing Seattle. The equivalent in lambda calculus is:\nλx.[x = Seattle].\n(2)\nIn general, for an entity e ∈E, e is a unary logical form representing the indicator function that\nreturns true when its argument is equal to e:\nJeK = λx.[x = e].\n(3)\nBinary base case\nThe next example is\nPlaceOfBirth,\n(4)\nwhich denotes the set of pairs of people and where they were born:\nλx.λy.PlaceOfBirth(x, y).\n(5)\nIn general, for a property p ∈P, p is a binary logical form, which denotes a function mapping two\narguments to whether p holds:\nJpK = λx.λy.p(x, y).\n(6)\nJoin\nThe most central operation in lambda DCS is join. For example, “people born in Seattle” is\nrepresented as\nPlaceOfBirth.Seattle\n(7)\nin lambda DCS and as\nλx.PlaceOfBirth(x, Seattle)\n(8)\n2\nin lambda calculus. In general, for a binary logical form b and unary logical form u, we have that\nb.u is a unary logical form which denotes:\nJb.uK = λx.∃y.JbK(x, y) ∧JuK(y).\n(9)\nThe key feature of a join is the implicit existential quantiﬁcation over the argument y shared by\nb and u. From a database perspective, this is simply a join over relations b and u on the second\nargument of b and the ﬁrst (and only) argument of u and then projecting out the joined variable.\nThe advantage of lambda DCS is more apparent when binaries are chained.\nFor example,\nconsider “those who had children born in Seattle”:\nChildren.PlaceOfBirth.Seattle,\n(10)\nand its lambda calculus equivalent:\nλx.∃y.Children(x, y) ∧PlaceOfBirth(y, Seattle).\n(11)\nHere, Children(x, y) denotes whether x has a child y and PlaceOfBirth(y, Seattle) denotes whether y\nwas born in Seattle.\nA logical form p1. · · · .pk.e corresponds to a chain-structured graph pattern on the knowledge\nbase K which matches any entity (node) which can reach e by following k edges labeled with the\ngiven properties p1, . . . , pk.\nIntersection\nThe set of scientists born in Seattle in lambda DCS:\nProfession.Scientist ⊓PlaceOfBirth.Seattle\n(12)\nand in lambda calculus:\nλx.Profession(x, Scientist) ∧PlaceOfBirth(x, Seattle).\n(13)\nIn general, for two unaries u1 and u2 u1 ⊓u2 is a unary logical form representing:\nJu1 ⊓u2K = λx.Ju1K(x) ∧Ju2K(x).\n(14)\nIn terms of the graph pattern perspective, intersection allows tree-structured graph patterns,\nwhere branch points correspond to the intersections.\nUnion\nWhereas intersection corresponds to conjunction, union corresponds to disjunction. The\nset containing “Oregon, Washington and Canadian provinces” in lambda DCS:\nOregon ⊔Washington ⊔Type.CanadianProvince\n(15)\nand in lambda calculus:\nλx.[x = Oregon] ∨[x = Washington] ∨Type(x, CanadianProvince).\n(16)\nIn general, for two unaries u1 and u2 u1 ⊔u2 is a unary logical form representing:\nJu1 ⊔u2K = λx.Ju1K(x) ∨Ju2K(x)\n(17)\n3\nNegation\nNegation is straightforward. Here is “states not bordering California” in lambda DCS:\nType.USState ⊓¬Border.California\n(18)\nand in lambda calculus:\nλx.Type(x, USState) ∧¬Border(x, California).\n(19)\nIn general, for a unary u,\nJ¬uK = λx.¬JuK(x).\n(20)\nHigher-order functions\nHigher-order functions operate on sets of entities rather than on indi-\nvidual entities. These include aggregation (counting, ﬁnding the min/max), superlatives (taking\nthe argmin/argmax), and generalized quantiﬁcation. In lambda DCS, these are implemented in\nthe natural way.\nFor example, the number of states and the number largest state by area are represented as\nfollows in lambda DCS:\ncount(Type.USState),\n(21)\nargmax(Type.USState, Area).\n(22)\nIn lambda calculus:\ncount(λx.Type(x, USState)),\n(23)\nargmax(λx.Type(x, USState), λx.λy.Area(x, y)).\n(24)\nIn general, for an aggregation operator A (e.g., count) and a unary u, we have:\nJA(u)K = λx.[x = A(JuK)].\n(25)\nFor a superlative operator S (e.g., argmax), unary u, and binary b:\nJS(u, b)K = λx.[x ∈S(JuK, JbK)].\n(26)\nLambda abstraction\nUp until now, our lambda DCS logical forms have been limited in two\nways:\n1. Fundamentally, our logical forms have been tree-structured, since the only way diﬀerent\nparts of the logical forms can currently interact is via one implicitly represented overlapping\nvariable. Non-tree-structured logical forms are important for handling bound anaphora, and\nto capture such phenomena, we will introduce a construct called mu abstraction.\n2. All our composition operations have created unaries. However, higher-order operations such\nas argmax take in a binary which supply the comparison function, which could be non-atomic.\nTo construct binaries compositionally, we introduce lambda abstraction, which is in general\ndistinct from lambda abstraction in lambda calculus, although the two coincide in some cases.\n4\nLet us start with an example of bound anaphora: “those who had a child who inﬂuenced them”.\nIn lambda DCS, we use mu abstraction:\nµx.Children.Influenced.x\n(27)\nHere, the µx simply adds a constraint that the ﬁrst argument of Children be bound to the second\nargument of Influenced. In lambda calculus, this expression is:\nλx.∃y.Children(x, y).Influenced(y, x).\n(28)\nLet us consider a superlative with a compositional comparison function: “person who has the\nmost children”. In lambda DCS, we use lambda abstraction to construct a new binary logical form\ndenoting pairs of people and the number of children they have:\nargmax(Type.Person, R[λx.count(R[Children].x])),\n(29)\nwhere we use the reverse operator JR[b]K = λy.λx.JbK(x, y) switches the arguments of b.\nThe equivalent logical form in lambda calculus:\nargmax(λx.Type(x, Person), λx.count(λz.Children(x, z))).\n(30)\nIn general, for a variable a ∈V and a unary u, we deﬁne the conversion for variables, mu\nabstraction, and lambda abstraction as follows:\nJaK = λx.[x = a],\n(31)\nJµa.uK = λx.[a = x] ∧JuK(x),\n(32)\nJλa.uK = λx.λa.JuK(x).\n(33)\nNote that applied to unaries, lambda abstraction produces binary logical forms, while mu abstrac-\ntion produces unary logical forms.\n2.1\nDiscussion\nA prevailing theme in lambda DCS is that the construction of logical forms centers around sets (of\nentities or entity pairs), whereas in lambda calculus, construction centers around truth values. Lift-\ning up to sets allows us to eliminate variables, treating them as implicitly existentially quantiﬁed.\nIndeed, looking back to the conversion function J·K, they all have the form JzK = λx.something.\nOf course, there are logical forms where lambda DCS would not oﬀer much savings in reduc-\ning variables—for example, when many predicates operate on the same variables in a non-tree-\nstructured manner. However, we have found that for logical forms derived from natural language,\nespecially for querying databases, lambda DCS is a good choice.\nThe development of lambda DCS has been inspired by many other formalisms. As evident by\nname, lambda DCS is adapted from Dependency-Based Compositional Semantics (DCS) (Liang et al.\n2011), which prominently features (i) tree-structured logical forms and (ii) default existential quan-\ntiﬁcation, the latter being imported from Discourse Representation Theory (Kamp and Reyle 1993).\nThere are two major diﬀerences between lambda DCS and DCS. First, lambda DCS revolves around\nunaries and binaries, which we found to be the right level of generality; DCS allowed arbitrary ar-\nities, and thus was a little too low-level. Second, we have omitted the mark-execute construct of\n5\nDCS, which is an orthogonal direction for future exploration. We can think of mark-execute as\nmore in the realm of constructing logical forms compositionally rather than their representation.\nWe have focused on the latter here.\nThe syntax of lambda DCS and the tree-structured nature (without variables) is derived from\nthe concept constructors in description logic (Baader 2003), but the marriage with variables and\nhigher-order functions is speciﬁc to lambda DCS. Of course, description logic is designed for logical\ninference, which necessitates a simpler logic, whereas lambda DCS is designed for model checking\n(e.g., querying a database), and can therefore bear the additional complexity.\nGiven our application to querying graph databases, it is natural that there are some parallels\nbetween lambda DCS and graph query languages such as SPARQL (Harris and Seaborne 2011), to\nwhich we ultimately convert in order to execute the logical forms (Berant et al. 2013). Working with\na graph database leads to thinking about logical forms as graph patterns, although this intuition\nis less helpful when we add higher-order operations.\nIn terms of expressivity, lambda DCS is clearly dominated by lambda calculus, as evident by\nour conversion from the former to the latter. From this perspective, lambda DCS is syntactic sugar.\nHowever, we believe that lambda DCS is more closely connected with the compositional structure\nof natural language and therefore can be quite convenient to work with.\nWe should also note that lambda calculus in formal semantics is really used for two purposes,\nwhich we’d like to dissect: The ﬁrst purpose is to construct the logical form of a sentence composi-\ntionally, where lambda abstraction is merely used as a macro to piece bits of logical form together.\nThe second purpose is to represent the ﬁnal logical form, where lambda abstraction is needed to de-\nnote a function (e.g., the comparison function passed into argmax). Here, we have mainly focused on\nthe latter representation issues. As for construction, we have so far used a very simple construction\nmechanism Berant et al. (2013), since we targeted the semantic parsing of short questions, which\nhave limited compositional demands. In principle, lambda DCS logical forms could be constructed\nusing lambda calculus (serving as a macro) in a CCG formalism. Analogously, lambda calculus has\nbeen used to build logical forms in Discourse Representation Theory (Muskens 1996). Down the\nroad, we hope that working with lambda DCS can lead to new construction mechanisms suitable\nfor complex sentences.\nReferences\nF. Baader. The description logic handbook: theory, implementation, and applications. Cambridge\nUniversity Press, 2003.\nJ. Berant, A. Chou, R. Frostig, and P. Liang. Semantic parsing on Freebase from question-answer\npairs. In Empirical Methods in Natural Language Processing (EMNLP), 2013.\nK. Bollacker, C. Evans, P. Paritosh, T. Sturge, and J. Taylor. Freebase: a collaboratively created\ngraph database for structuring human knowledge. In International Conference on Management\nof Data (SIGMOD), pages 1247–1250, 2008.\nB. Carpenter. Type-Logical Semantics. MIT Press, 1998.\nS. Harris and A. Seaborne. SPARQL 1.1 query language. In W3C Working Draft, 12 May, 2011.\n6\nH. Kamp and U. Reyle. From Discourse to Logic: An Introduction to the Model-theoretic Semantics\nof Natural Language, Formal Logic and Discourse Representation Theory. Kluwer, Dordrecht,\n1993.\nP. Liang, M. I. Jordan, and D. Klein. Learning dependency-based compositional semantics. In\nAssociation for Computational Linguistics (ACL), pages 590–599, 2011.\nR. Muskens. Combining montague semantics and discourse representation. Linguistics and Philos-\nophy, 19(2):143–186, 1996.\n7\n'

In [11]:
df['full_text'] = df['full_text'].str.replace('\n', ' ')

In [12]:
df.iloc[5555,5]

'arXiv:1309.4408v2  [cs.AI]  18 Sep 2013 Lambda Dependency-Based Compositional Semantics Percy Liang September 19, 2013 Abstract This short note presents a new formal language, lambda dependency-based compositional semantics (lambda DCS) for representing logical forms in semantic parsing. By eliminating variables and making existential quantiﬁcation implicit, lambda DCS logical forms are generally more compact than those in lambda calculus. 1 Introduction Semantic parsing is the task of mapping natural language utterances to logical forms in some formal language such as lambda calculus. This short note describes lambda dependency-based compositional semantics (lambda DCS), an alternate formal language which can be notationally simpler than lambda calculus. Here is an example:1 • Utterance: “people who have lived in Seattle” • Logical form (lambda calculus): λx.∃e.PlacesLived(x, e) ∧Location(e, Seattle) • Logical form (lambda DCS): PlacesLived.Location.Seattle As one can see, lambda DCS attempts to remove explicit use of variables. This makes it simi- lar in spirit to dependency-based compositional semantics (DCS) (Liang et al. 2011), but DCS is restricted to tree-structured logical forms, and is therefore not as expressive as lambda calculus. Lambda DCS, on the other hand, borrows the use of variables and lambda abstraction from lambda calculus when necessary to handle phenomena such as anaphora. Lambda DCS was designed in the context of building a natural language interface into Free- base (Bollacker et al. 2008), a large graph database, where the logical forms are database queries (see Berant et al. (2013) for our companion paper). Therefore, we will focus on representing the semantics of noun phrases or wh-questions. Also, we will discuss only the semantics of the formal language, not the compositional semantics of mapping natural language utterances into lambda DCS. Finally, this document assumes the reader has basic familiarity with lambda calculus in the context of natural language (see Carpenter (1998) for an introduction). 1This example is based on the Freebase schema, which reiﬁes events (called compound value types in Freebase). Here, PlacesLived(x, e) denotes that a person x was involved in a living event e, and Location(e, Seattle) denotes that the location of that event is Seattle. Other properties of e would include StartDate(e, ·) and EndDate(e, ·). 1 2 Deﬁnition We now present the full deﬁnition of lambda DCS. In the background, we have a knowledge base of assertions. Let E be a set of entities (e.g., Seattle ∈E), P be the set of properties (e.g., PlaceOfBirth ∈E). Then K ⊂E ×P ×E is the knowledge base, which can be visualized as a directed graph where nodes are entities and edges represent assertions in the knowledge graph. Also, let V be a set of variables (e.g., x1, x2 ∈V). Let [condition] denote the truth value of the condition. For example, λx.[x = 3] denotes the function that returns true if and only if its argument is equal to 3. We will now walk through each of the constructs in lambda DCS with concrete examples, and also provide a formal deﬁnition of their semantics by providing a formal conversion to equivalent lambda calculus forms. Notationally, let JzK be the lambda calculus form corresponding to the lambda DCS form z. In the following deﬁnitions, let x, y denote fresh variables which are not used anywhere else. Unary base case The simplest lambda DCS form is a single entity. For example, Seattle (1) denotes the singleton set containing Seattle. The equivalent in lambda calculus is: λx.[x = Seattle]. (2) In general, for an entity e ∈E, e is a unary logical form representing the indicator function that returns true when its argument is equal to e: JeK = λx.[x = e]. (3) Binary base case The next example is PlaceOfBirth, (4) which denotes the set of pairs of people and where they were born: λx.λy.PlaceOfBirth(x, y). (5) In general, for a property p ∈P, p is a binary logical form, which denotes a function mapping two arguments to whether p holds: JpK = λx.λy.p(x, y). (6) Join The most central operation in lambda DCS is join. For example, “people born in Seattle” is represented as PlaceOfBirth.Seattle (7) in lambda DCS and as λx.PlaceOfBirth(x, Seattle) (8) 2 in lambda calculus. In general, for a binary logical form b and unary logical form u, we have that b.u is a unary logical form which denotes: Jb.uK = λx.∃y.JbK(x, y) ∧JuK(y). (9) The key feature of a join is the implicit existential quantiﬁcation over the argument y shared by b and u. From a database perspective, this is simply a join over relations b and u on the second argument of b and the ﬁrst (and only) argument of u and then projecting out the joined variable. The advantage of lambda DCS is more apparent when binaries are chained. For example, consider “those who had children born in Seattle”: Children.PlaceOfBirth.Seattle, (10) and its lambda calculus equivalent: λx.∃y.Children(x, y) ∧PlaceOfBirth(y, Seattle). (11) Here, Children(x, y) denotes whether x has a child y and PlaceOfBirth(y, Seattle) denotes whether y was born in Seattle. A logical form p1. · · · .pk.e corresponds to a chain-structured graph pattern on the knowledge base K which matches any entity (node) which can reach e by following k edges labeled with the given properties p1, . . . , pk. Intersection The set of scientists born in Seattle in lambda DCS: Profession.Scientist ⊓PlaceOfBirth.Seattle (12) and in lambda calculus: λx.Profession(x, Scientist) ∧PlaceOfBirth(x, Seattle). (13) In general, for two unaries u1 and u2 u1 ⊓u2 is a unary logical form representing: Ju1 ⊓u2K = λx.Ju1K(x) ∧Ju2K(x). (14) In terms of the graph pattern perspective, intersection allows tree-structured graph patterns, where branch points correspond to the intersections. Union Whereas intersection corresponds to conjunction, union corresponds to disjunction. The set containing “Oregon, Washington and Canadian provinces” in lambda DCS: Oregon ⊔Washington ⊔Type.CanadianProvince (15) and in lambda calculus: λx.[x = Oregon] ∨[x = Washington] ∨Type(x, CanadianProvince). (16) In general, for two unaries u1 and u2 u1 ⊔u2 is a unary logical form representing: Ju1 ⊔u2K = λx.Ju1K(x) ∨Ju2K(x) (17) 3 Negation Negation is straightforward. Here is “states not bordering California” in lambda DCS: Type.USState ⊓¬Border.California (18) and in lambda calculus: λx.Type(x, USState) ∧¬Border(x, California). (19) In general, for a unary u, J¬uK = λx.¬JuK(x). (20) Higher-order functions Higher-order functions operate on sets of entities rather than on indi- vidual entities. These include aggregation (counting, ﬁnding the min/max), superlatives (taking the argmin/argmax), and generalized quantiﬁcation. In lambda DCS, these are implemented in the natural way. For example, the number of states and the number largest state by area are represented as follows in lambda DCS: count(Type.USState), (21) argmax(Type.USState, Area). (22) In lambda calculus: count(λx.Type(x, USState)), (23) argmax(λx.Type(x, USState), λx.λy.Area(x, y)). (24) In general, for an aggregation operator A (e.g., count) and a unary u, we have: JA(u)K = λx.[x = A(JuK)]. (25) For a superlative operator S (e.g., argmax), unary u, and binary b: JS(u, b)K = λx.[x ∈S(JuK, JbK)]. (26) Lambda abstraction Up until now, our lambda DCS logical forms have been limited in two ways: 1. Fundamentally, our logical forms have been tree-structured, since the only way diﬀerent parts of the logical forms can currently interact is via one implicitly represented overlapping variable. Non-tree-structured logical forms are important for handling bound anaphora, and to capture such phenomena, we will introduce a construct called mu abstraction. 2. All our composition operations have created unaries. However, higher-order operations such as argmax take in a binary which supply the comparison function, which could be non-atomic. To construct binaries compositionally, we introduce lambda abstraction, which is in general distinct from lambda abstraction in lambda calculus, although the two coincide in some cases. 4 Let us start with an example of bound anaphora: “those who had a child who inﬂuenced them”. In lambda DCS, we use mu abstraction: µx.Children.Influenced.x (27) Here, the µx simply adds a constraint that the ﬁrst argument of Children be bound to the second argument of Influenced. In lambda calculus, this expression is: λx.∃y.Children(x, y).Influenced(y, x). (28) Let us consider a superlative with a compositional comparison function: “person who has the most children”. In lambda DCS, we use lambda abstraction to construct a new binary logical form denoting pairs of people and the number of children they have: argmax(Type.Person, R[λx.count(R[Children].x])), (29) where we use the reverse operator JR[b]K = λy.λx.JbK(x, y) switches the arguments of b. The equivalent logical form in lambda calculus: argmax(λx.Type(x, Person), λx.count(λz.Children(x, z))). (30) In general, for a variable a ∈V and a unary u, we deﬁne the conversion for variables, mu abstraction, and lambda abstraction as follows: JaK = λx.[x = a], (31) Jµa.uK = λx.[a = x] ∧JuK(x), (32) Jλa.uK = λx.λa.JuK(x). (33) Note that applied to unaries, lambda abstraction produces binary logical forms, while mu abstrac- tion produces unary logical forms. 2.1 Discussion A prevailing theme in lambda DCS is that the construction of logical forms centers around sets (of entities or entity pairs), whereas in lambda calculus, construction centers around truth values. Lift- ing up to sets allows us to eliminate variables, treating them as implicitly existentially quantiﬁed. Indeed, looking back to the conversion function J·K, they all have the form JzK = λx.something. Of course, there are logical forms where lambda DCS would not oﬀer much savings in reduc- ing variables—for example, when many predicates operate on the same variables in a non-tree- structured manner. However, we have found that for logical forms derived from natural language, especially for querying databases, lambda DCS is a good choice. The development of lambda DCS has been inspired by many other formalisms. As evident by name, lambda DCS is adapted from Dependency-Based Compositional Semantics (DCS) (Liang et al. 2011), which prominently features (i) tree-structured logical forms and (ii) default existential quan- tiﬁcation, the latter being imported from Discourse Representation Theory (Kamp and Reyle 1993). There are two major diﬀerences between lambda DCS and DCS. First, lambda DCS revolves around unaries and binaries, which we found to be the right level of generality; DCS allowed arbitrary ar- ities, and thus was a little too low-level. Second, we have omitted the mark-execute construct of 5 DCS, which is an orthogonal direction for future exploration. We can think of mark-execute as more in the realm of constructing logical forms compositionally rather than their representation. We have focused on the latter here. The syntax of lambda DCS and the tree-structured nature (without variables) is derived from the concept constructors in description logic (Baader 2003), but the marriage with variables and higher-order functions is speciﬁc to lambda DCS. Of course, description logic is designed for logical inference, which necessitates a simpler logic, whereas lambda DCS is designed for model checking (e.g., querying a database), and can therefore bear the additional complexity. Given our application to querying graph databases, it is natural that there are some parallels between lambda DCS and graph query languages such as SPARQL (Harris and Seaborne 2011), to which we ultimately convert in order to execute the logical forms (Berant et al. 2013). Working with a graph database leads to thinking about logical forms as graph patterns, although this intuition is less helpful when we add higher-order operations. In terms of expressivity, lambda DCS is clearly dominated by lambda calculus, as evident by our conversion from the former to the latter. From this perspective, lambda DCS is syntactic sugar. However, we believe that lambda DCS is more closely connected with the compositional structure of natural language and therefore can be quite convenient to work with. We should also note that lambda calculus in formal semantics is really used for two purposes, which we’d like to dissect: The ﬁrst purpose is to construct the logical form of a sentence composi- tionally, where lambda abstraction is merely used as a macro to piece bits of logical form together. The second purpose is to represent the ﬁnal logical form, where lambda abstraction is needed to de- note a function (e.g., the comparison function passed into argmax). Here, we have mainly focused on the latter representation issues. As for construction, we have so far used a very simple construction mechanism Berant et al. (2013), since we targeted the semantic parsing of short questions, which have limited compositional demands. In principle, lambda DCS logical forms could be constructed using lambda calculus (serving as a macro) in a CCG formalism. Analogously, lambda calculus has been used to build logical forms in Discourse Representation Theory (Muskens 1996). Down the road, we hope that working with lambda DCS can lead to new construction mechanisms suitable for complex sentences. References F. Baader. The description logic handbook: theory, implementation, and applications. Cambridge University Press, 2003. J. Berant, A. Chou, R. Frostig, and P. Liang. Semantic parsing on Freebase from question-answer pairs. In Empirical Methods in Natural Language Processing (EMNLP), 2013. K. Bollacker, C. Evans, P. Paritosh, T. Sturge, and J. Taylor. Freebase: a collaboratively created graph database for structuring human knowledge. In International Conference on Management of Data (SIGMOD), pages 1247–1250, 2008. B. Carpenter. Type-Logical Semantics. MIT Press, 1998. S. Harris and A. Seaborne. SPARQL 1.1 query language. In W3C Working Draft, 12 May, 2011. 6 H. Kamp and U. Reyle. From Discourse to Logic: An Introduction to the Model-theoretic Semantics of Natural Language, Formal Logic and Discourse Representation Theory. Kluwer, Dordrecht, 1993. P. Liang, M. I. Jordan, and D. Klein. Learning dependency-based compositional semantics. In Association for Computational Linguistics (ACL), pages 590–599, 2011. R. Muskens. Combining montague semantics and discourse representation. Linguistics and Philos- ophy, 19(2):143–186, 1996. 7 '

### **Subsetting Data**
---

In [13]:
df.iloc[153,3]

'2000-01-19'

In [14]:
df = df.iloc[153:]

In [15]:
df.shape

(87984, 6)

In [16]:
df.head()['published_date']

157    2000-01-19
158    2000-01-04
159    2000-02-27
160    2000-02-24
161    2000-02-24
Name: published_date, dtype: object

In [17]:
df.tail()['published_date']

89370    2024-12-01
89371    2024-12-01
89372    2024-12-01
89373    2024-12-01
89374    2024-12-01
Name: published_date, dtype: object

In [18]:
df.head()

,id,title,authors,published_date,pdf_url,full_text
157,http://arxiv.org/abs/cs/0001015v1,Multi-Agent Only Knowing,"['Joseph Y. Halpern', 'Gerhard Lakemeyer']",2000-01-19,http://arxiv.org/pdf/cs/0001015v1,arXiv:cs/0001015v1 [cs.AI] 19 Jan 2000 Multi...
158,http://arxiv.org/abs/cs/0001002v1,Minimum Description Length and Compositionality,['Wlodek Zadrozny'],2000-01-04,http://arxiv.org/pdf/cs/0001002v1,arXiv:cs/0001002v1 [cs.CL] 4 Jan 2000 Minimu...
159,http://arxiv.org/abs/cs/0002016v3,SLT-Resolution for the Well-Founded Semantics,"['Yi-Dong Shen', 'Li-Yan Yuan', 'Jia-Huai You']",2000-02-27,http://arxiv.org/pdf/cs/0002016v3,arXiv:cs/0002016v3 [cs.AI] 2 Mar 2001 SLT-Re...
160,http://arxiv.org/abs/cs/0002014v1,Safe cooperative robot dynamics on graphs,"['Robert Ghrist', 'Daniel Koditschek']",2000-02-24,http://arxiv.org/pdf/cs/0002014v1,arXiv:cs/0002014v1 [cs.RO] 24 Feb 2000 Safe ...
161,http://arxiv.org/abs/cs/0002015v1,Genetic Algorithms for Extension Search in Def...,"['P. Nicolas', 'F. Saubion', 'I. Stephan']",2000-02-24,http://arxiv.org/pdf/cs/0002015v1,arXiv:cs/0002015v1 [cs.AI] 24 Feb 2000 Genet...

In [19]:
df.reset_index(drop=True, inplace=True)

In [20]:
df.head()

,id,title,authors,published_date,pdf_url,full_text
0,http://arxiv.org/abs/cs/0001015v1,Multi-Agent Only Knowing,"['Joseph Y. Halpern', 'Gerhard Lakemeyer']",2000-01-19,http://arxiv.org/pdf/cs/0001015v1,arXiv:cs/0001015v1 [cs.AI] 19 Jan 2000 Multi...
1,http://arxiv.org/abs/cs/0001002v1,Minimum Description Length and Compositionality,['Wlodek Zadrozny'],2000-01-04,http://arxiv.org/pdf/cs/0001002v1,arXiv:cs/0001002v1 [cs.CL] 4 Jan 2000 Minimu...
2,http://arxiv.org/abs/cs/0002016v3,SLT-Resolution for the Well-Founded Semantics,"['Yi-Dong Shen', 'Li-Yan Yuan', 'Jia-Huai You']",2000-02-27,http://arxiv.org/pdf/cs/0002016v3,arXiv:cs/0002016v3 [cs.AI] 2 Mar 2001 SLT-Re...
3,http://arxiv.org/abs/cs/0002014v1,Safe cooperative robot dynamics on graphs,"['Robert Ghrist', 'Daniel Koditschek']",2000-02-24,http://arxiv.org/pdf/cs/0002014v1,arXiv:cs/0002014v1 [cs.RO] 24 Feb 2000 Safe ...
4,http://arxiv.org/abs/cs/0002015v1,Genetic Algorithms for Extension Search in Def...,"['P. Nicolas', 'F. Saubion', 'I. Stephan']",2000-02-24,http://arxiv.org/pdf/cs/0002015v1,arXiv:cs/0002015v1 [cs.AI] 24 Feb 2000 Genet...

In [21]:
df.tail()

,id,title,authors,published_date,pdf_url,full_text
87979,http://arxiv.org/abs/2412.00653v1,Predictive Inference With Fast Feature Conform...,"['Zihao Tang', 'Boyuan Wang', 'Chuan Wen', 'Ji...",2024-12-01,http://arxiv.org/pdf/2412.00653v1,Predictive Inference With Fast Feature Conform...
87980,http://arxiv.org/abs/2412.00631v2,ROSE: A Reward-Oriented Data Selection Framewo...,"['Yang Wu', 'Huayi Zhang', 'Yizheng Jiao', 'Li...",2024-12-01,http://arxiv.org/pdf/2412.00631v2,ROSE: A Reward-Oriented Data Selection Framewo...
87981,http://arxiv.org/abs/2412.00627v2,ARChef: An iOS-Based Augmented Reality Cooking...,"['Rithik Vir', 'Parsa Madinei']",2024-12-01,http://arxiv.org/pdf/2412.00627v2,ARChef: An iOS-Based Augmented Reality Cooking...
87982,http://arxiv.org/abs/2412.00622v2,Visual Modality Prompt for Adapting Vision-Lan...,"['Heitor R. Medeiros', 'Atif Belal', 'Srikanth...",2024-12-01,http://arxiv.org/pdf/2412.00622v2,Visual Modality Prompt for Adapting Vision-Lan...
87983,http://arxiv.org/abs/2412.00621v1,Exposing LLM Vulnerabilities: Adversarial Scam...,"['Chen-Wei Chang', 'Shailik Sarkar', 'Shutonu ...",2024-12-01,http://arxiv.org/pdf/2412.00621v1,Exposing LLM Vulnerabilities: Adversarial Scam...

In [22]:
df.shape[0]-1

87983

In [23]:
df.to_csv('final_data.csv', index=False)